### ISSUE TITLE
子应用样式隔离失效

### ISSUE THREAD

**Issue by lxly** [jd-opensource/micro-app#1345]
## 问题描述
> 子应用中的样式使用html嵌套时，样式隔离失效

## 复现步骤
1.子应用设置.content样式，样式如图1
```css
html .content{
  background: #00f;
}
```
2.子应用设置.content样式，样式如图2
```css
html {
  .content{
    background: #fff
  }
}
```

## 上传截图
> 
<img width="767" alt="1" src="https://github.com/user-attachments/assets/992c4e5c-0ad6-47fd-b322-2f1d71291dfa">
<img width="770" alt="2" src="https://github.com/user-attachments/assets/da03d1c8-5f01-4fa7-992b-6a114a60ac4d">

## 复现仓库
>https://github.com/lxly/micro-app-bug-demo

## 环境信息
- micro-app版本：1.0.0-rc.6
- 主应用前端框架&版本：vue@3.4.31
- 子应用前端框架&版本：vue@3.4.31
- 构建工具&版本：vite@5.3.3
