### ISSUE TITLE
当子应用样式引入的字体文件含有括号的时候,会导致样式全部失效。

### ISSUE THREAD

**Issue by YFAnt** [jd-opensource/micro-app#1460]
## 问题描述
> 问题的具体描述
有一个字体文件 文件名是这样的
```css
/* 全局字体 */
@font-face {
  font-family: RuiZiAoYunJingShenPinBoJianMianFei-Shan;
  src: url("./RuiZiAoYunJingShenPinBoJianMianFei-Shan(REEJI-PinboGB-Flash)-2.ttf");
}
```
这个嵌入到micro 解析的时候 会变成
```css
 url("域名+ 路径+ RuiZiAoYunJingShenPinBoJianMianFei-Shan(REEJI-PinboGB-Flash")-2.ttf")
```
多了一个” 号，导致后续的css失效

<img width="1217" alt="image" src="https://github.com/user-attachments/assets/a329bda7-9ba6-4c68-b54d-ca6dd0c34c6e">
这个正则有点问题，

## 复现步骤
1.
2.

## 上传截图
> 请上传代码截图、控制台、终端等截图以帮助我们了解您的问题。

## 复现仓库
> 请提供一个精简的代码仓库，然后上传到自己的 github，以帮助我们复现您的问题。

## 环境信息
- micro-app版本：1.0.0-rc15
- 主应用前端框架&版本：
- 子应用前端框架&版本：
- 构建工具&版本：
