### ISSUE TITLE
【BUG】当开启样式隔离时子应用属性选择器样式错误

### ISSUE THREAD

**Issue by uioonm** [jd-opensource/micro-app#1553]
## 问题描述
> 问题的具体描述

子应用的设置多个属性选择器样式时，后者会覆盖前者，如果取消样式隔离则没有这个问题

## 复现步骤
1.设置以下并引入
```css
.test[data-selection-length="0"],
.test[data-selection-length="1"] {
    display: none;
}
```
2. 最后子应用的样式变为
```css
.test[data-selection-length="1"],
.test[data-selection-length="1"] {
    display: none;
}
```
后者会覆盖前者例如
```css
.test[data-selection-length="1"],
.test[data-selection-length="0"] {
    display: none;
}
```
则会变成
```css
.test[data-selection-length="0"],
.test[data-selection-length="0"] {
    display: none;
}
```
开启disableScopecss则正常
## 上传截图
> 请上传代码截图、控制台、终端等截图以帮助我们了解您的问题。

![Image](https://github.com/user-attachments/assets/cd587460-fcf9-41fe-a695-7fed5f6fc0d9)

## 复现仓库
>https://github.com/uioonm/microApp-demo
## 环境信息
- micro-app版本：1.0.0-rc.20
- 主应用前端框架&版本：react18
- 子应用前端框架&版本：react18
- 构建工具&版本：rspack
